#!/usr/bin/env node
/**
 * Generates js/config.js at deploy time from the FIREBASE_CONFIG_JSON env var.
 *
 * FAILS the build if the env var is missing, malformed, or missing required
 * Firebase fields. Silently continuing would ship a broken app to GitHub
 * Pages (the "Configuration Required" overlay would show), so fail loud.
 *
 * Usage in CI (GitHub Actions):
 *   node scripts/build-config.js   # env var read from process.env
 *
 * Usage locally to test the script:
 *   FIREBASE_CONFIG_JSON='{"apiKey":"...","projectId":"...",...}' \
 *     node scripts/build-config.js
 */
const fs   = require('fs');
const path = require('path');

function fail(msg) {
  console.error('build-config: ' + msg);
  process.exit(1);
}

const raw = process.env.FIREBASE_CONFIG_JSON;
if (!raw) fail('FIREBASE_CONFIG_JSON env var is required.');

let parsed;
try { parsed = JSON.parse(raw); }
catch (e) { fail('FIREBASE_CONFIG_JSON is not valid JSON: ' + e.message); }

const required = ['apiKey', 'projectId', 'authDomain', 'appId'];
const missing  = required.filter(k => typeof parsed[k] !== 'string' || !parsed[k]);
if (missing.length) fail('FIREBASE_CONFIG_JSON is missing fields: ' + missing.join(', '));

const minified = JSON.stringify(parsed);
fs.mkdirSync(path.join(__dirname, '..', 'js'), { recursive: true });
fs.writeFileSync(
  path.join(__dirname, '..', 'js', 'config.js'),
  '// GENERATED by scripts/build-config.js at deploy time. Do not edit.\n' +
  'window.firebaseConfig = ' + minified + ';\n'
);
console.log('Wrote js/config.js with Firebase project:', parsed.projectId);
